### ISSUE TITLE
Building fails on Mac OS 10.13

### ISSUE THREAD

**Issue by Euphorbium** [VCVRack/Rack#122]
OS : Mac OS 10.12.6
Version: dev

I had to update the sysroot path to 10.13 and minimal macosx version to 10.11 in `compile.mk` and in `dep/Makefile`  to progress through some issues, but now I am getting:
```
macbooks-MacBook-Pro:Rack euphorbium$ sudo make
Password:
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.11 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/gui.cpp.o src/gui.cpp
In file included from src/gui.cpp:3:
include/gui.hpp:4:10: fatal error: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
         ^~~~~~~~~~~~~~
1 error generated.
make: *** [build/src/gui.cpp.o] Error 1
```

**Comment by AndrewBelt** [comment]
Did the glfw build fail?

**Comment by Euphorbium** [comment]
I got the message `# Built all dependencies successfully #`

**Comment by Euphorbium** [comment]
Rerun everything from the start and observed more carefully. A bunch of dependancy building stuff failed. It seems like it needs some work to build on 10.12.6

**Comment by AndrewBelt** [comment]
What's the first build issue? We can work on it one at a time, since it will help others with the same issue.

**Comment by Euphorbium** [comment]
Glfw fails to build. First there is a lot of warning, but if I keep minimal mac-os-x version there is only 3 warnings. But it still fails. Here is a relevant part of the build with.

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C glfw-3.2.1
Scanning dependencies of target glfw
[  1%] Building C object src/CMakeFiles/glfw.dir/context.c.o
[  2%] Building C object src/CMakeFiles/glfw.dir/init.c.o
[  3%] Building C object src/CMakeFiles/glfw.dir/input.c.o
[  4%] Building C object src/CMakeFiles/glfw.dir/monitor.c.o
[  5%] Building C object src/CMakeFiles/glfw.dir/vulkan.c.o
[  6%] Building C object src/CMakeFiles/glfw.dir/window.c.o
[  7%] Building C object src/CMakeFiles/glfw.dir/cocoa_init.m.o
[  8%] Building C object src/CMakeFiles/glfw.dir/cocoa_joystick.m.o
[  9%] Building C object src/CMakeFiles/glfw.dir/cocoa_monitor.m.o
/Users/euphorbium/experiments/Rack/dep/glfw-3.2.1/src/cocoa_monitor.m:50:42: warning: 
      'CGDisplayIOServicePort' is deprecated: first deprecated in macOS 10.9
      [-Wdeprecated-declarations]
    info = IODisplayCreateInfoDictionary(CGDisplayIOServicePort(displayID),
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDisplayConfiguration.h:372:24: note: 
      'CGDisplayIOServicePort' has been explicitly marked deprecated here
CG_EXTERN io_service_t CGDisplayIOServicePort(CGDirectDisplayID display)
                       ^
/Users/euphorbium/experiments/Rack/dep/glfw-3.2.1/src/cocoa_monitor.m:89:26: warning: 
      'CGDisplayModeCopyPixelEncoding' is deprecated: first deprecated in macOS
      10.11 [-Wdeprecated-declarations]
    CFStringRef format = CGDisplayModeCopyPixelEncoding(mode);
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:176:34: note: 
      'CGDisplayModeCopyPixelEncoding' has been explicitly marked deprecated
      here
CG_EXTERN CFStringRef __nullable CGDisplayModeCopyPixelEncoding(
                                 ^
/Users/euphorbium/experiments/Rack/dep/glfw-3.2.1/src/cocoa_monitor.m:118:26: warning: 
      'CGDisplayModeCopyPixelEncoding' is deprecated: first deprecated in macOS
      10.11 [-Wdeprecated-declarations]
    CFStringRef format = CGDisplayModeCopyPixelEncoding(mode);
                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGDirectDisplay.h:176:34: note: 
      'CGDisplayModeCopyPixelEncoding' has been explicitly marked deprecated
      here
CG_EXTERN CFStringRef __nullable CGDisplayModeCopyPixelEncoding(
                                 ^
3 warnings generated.
[ 10%] Building C object src/CMakeFiles/glfw.dir/cocoa_window.m.o
[ 11%] Building C object src/CMakeFiles/glfw.dir/cocoa_time.c.o
[ 12%] Building C object src/CMakeFiles/glfw.dir/posix_tls.c.o
[ 13%] Building C object src/CMakeFiles/glfw.dir/nsgl_context.m.o
[ 14%] Linking C shared library libglfw.dylib
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

make[4]: *** [src/libglfw.dylib] Abort trap: 6
make[4]: *** Deleting file `src/libglfw.dylib'
make[3]: *** [src/CMakeFiles/glfw.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [glfw-3.2.1] Error 2
make: *** [dep] Error 2
```

**Comment by Euphorbium** [comment]
This could be helpfull here: https://github.com/simbody/simbody/pull/524

**Comment by Euphorbium** [comment]
Cmake is not going to cut it here: https://forums.developer.apple.com/thread/87097 
I've tried building with gcc. Glfw seems to get built, but libcurl fails to build with 10.7 build target

```
configure: Configured to build curl/libcurl:

  curl version:     7.54.1
  Host setup:       x86_64-apple-darwin16.7.0
  Install prefix:   /Users/euphorbium/experiments/Rack
  Compiler:         gcc
  SSL support:      no      (--with-{ssl,gnutls,nss,polarssl,mbedtls,cyassl,axtls,winssl,darwinssl} )
  SSH support:      no      (--with-libssh2)
  zlib support:     no      (--with-zlib)
  GSS-API support:  no      (--with-gssapi)
  TLS-SRP support:  no      (--enable-tls-srp)
  resolver:         default (--enable-ares / --enable-threaded-resolver)
  IPv6 support:     enabled
  Unix sockets support: enabled
  IDN support:      no      (--with-{libidn2,winidn})
  Build libcurl:    Shared=yes, Static=yes
  Built-in manual:  no      (--enable-manual)
  --libcurl option: enabled (--disable-libcurl-option)
  Verbose errors:   enabled (--disable-verbose)
  SSPI support:     no      (--enable-sspi)
  ca cert bundle:   no
  ca cert path:     no
  ca fallback:      no
  LDAP support:     no      (--enable-ldap / --with-ldap-lib / --with-lber-lib)
  LDAPS support:    no      (--enable-ldaps)
  RTSP support:     no      (--enable-rtsp)
  RTMP support:     no      (--with-librtmp)
  metalink support: no      (--with-libmetalink)
  PSL support:      no      (--with-libpsl)
  HTTP2 support:    disabled (--with-nghttp2)
  Protocols:        HTTP

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C curl-7.54.1
Making all in lib
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       libcurl_la-file.lo
  CC       libcurl_la-timeval.lo
  CC       libcurl_la-base64.lo
  CC       libcurl_la-hostip.lo
  CC       libcurl_la-progress.lo
  CC       libcurl_la-formdata.lo
  CC       libcurl_la-cookie.lo
  CC       libcurl_la-http.lo
  CC       libcurl_la-sendf.lo
  CC       libcurl_la-ftp.lo
  CC       libcurl_la-url.lo
  CC       libcurl_la-dict.lo
  CC       libcurl_la-if2ip.lo
  CC       libcurl_la-speedcheck.lo
  CC       libcurl_la-ldap.lo
  CC       libcurl_la-version.lo
  CC       libcurl_la-getenv.lo
  CC       libcurl_la-escape.lo
  CC       libcurl_la-mprintf.lo
  CC       libcurl_la-telnet.lo
  CC       libcurl_la-netrc.lo
  CC       libcurl_la-getinfo.lo
  CC       libcurl_la-transfer.lo
  CC       libcurl_la-strcase.lo
  CC       libcurl_la-easy.lo
  CC       libcurl_la-security.lo
  CC       libcurl_la-curl_fnmatch.lo
  CC       libcurl_la-fileinfo.lo
  CC       libcurl_la-ftplistparser.lo
  CC       libcurl_la-wildcard.lo
  CC       libcurl_la-krb5.lo
  CC       libcurl_la-memdebug.lo
  CC       libcurl_la-http_chunks.lo
  CC       libcurl_la-strtok.lo
  CC       libcurl_la-connect.lo
connect.c:1086:12: error: 'connectx' is only available on macOS 10.11 or newer
      [-Werror,-Wunguarded-availability]
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include/sys/socket.h:713:5: note: 
      'connectx' has been explicitly marked partial here
int connectx(int, const sa_endpoints_t *, sae_associd_t, unsigned int,
    ^
connect.c:1086:12: note: enclose 'connectx' in a __builtin_available check to
      silence this warning
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
1 error generated.
make[4]: *** [libcurl_la-connect.lo] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [curl-7.54.1] Error 2
make: *** [dep] Error 2
```

**Comment by AndrewBelt** [comment]
Weird. Are you using the MacOSX10.7 SDK?

**Comment by Euphorbium** [comment]
This is the version that appears in xcode app? It is 10.13, 10.7 is ancient.

**Comment by Euphorbium** [comment]
It seems like glfw does not get built after all. I've repeated the process with gcc and 10.11 build target:
```

Saving to: 'glfw-3.2.1.zip'

glfw-3.2.1.zip      100%[===================>]   1.09M  1003KB/s    in 1.1s    

2017-09-21 23:06:23 (1003 KB/s) - 'glfw-3.2.1.zip' saved [1144633/1144633]

unzip glfw-3.2.1.zip
Archive:  glfw-3.2.1.zip
   creating: glfw-3.2.1/
  inflating: glfw-3.2.1/.travis.yml  
   creating: glfw-3.2.1/include/
   creating: glfw-3.2.1/include/GLFW/
  inflating: glfw-3.2.1/include/GLFW/glfw3.h  
  inflating: glfw-3.2.1/include/GLFW/glfw3native.h  
  inflating: glfw-3.2.1/.appveyor.yml  
  inflating: glfw-3.2.1/COPYING.txt  
   creating: glfw-3.2.1/examples/
  inflating: glfw-3.2.1/examples/particles.c  
  inflating: glfw-3.2.1/examples/simple.c  
  inflating: glfw-3.2.1/examples/glfw.rc  
  inflating: glfw-3.2.1/examples/glfw.ico  
  inflating: glfw-3.2.1/examples/heightmap.c  
  inflating: glfw-3.2.1/examples/CMakeLists.txt  
  inflating: glfw-3.2.1/examples/gears.c  
  inflating: glfw-3.2.1/examples/wave.c  
  inflating: glfw-3.2.1/examples/splitview.c  
  inflating: glfw-3.2.1/examples/boing.c  
  inflating: glfw-3.2.1/examples/glfw.icns  
   creating: glfw-3.2.1/docs/
  inflating: glfw-3.2.1/docs/moving.dox  
  inflating: glfw-3.2.1/docs/monitor.dox  
  inflating: glfw-3.2.1/docs/spaces.svg  
  inflating: glfw-3.2.1/docs/compile.dox  
  inflating: glfw-3.2.1/docs/DoxygenLayout.xml  
  inflating: glfw-3.2.1/docs/extra.less  
  inflating: glfw-3.2.1/docs/vulkan.dox  
  inflating: glfw-3.2.1/docs/build.dox  
  inflating: glfw-3.2.1/docs/header.html  
  inflating: glfw-3.2.1/docs/context.dox  
  inflating: glfw-3.2.1/docs/main.dox  
  inflating: glfw-3.2.1/docs/CMakeLists.txt  
  inflating: glfw-3.2.1/docs/news.dox  
  inflating: glfw-3.2.1/docs/window.dox  
  inflating: glfw-3.2.1/docs/internal.dox  
  inflating: glfw-3.2.1/docs/input.dox  
  inflating: glfw-3.2.1/docs/quick.dox  
  inflating: glfw-3.2.1/docs/extra.css  
  inflating: glfw-3.2.1/docs/compat.dox  
  inflating: glfw-3.2.1/docs/footer.html  
   creating: glfw-3.2.1/docs/html/
  inflating: glfw-3.2.1/docs/html/globals_defs_o.html  
  inflating: glfw-3.2.1/docs/html/build_8dox.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_b.html  
  inflating: glfw-3.2.1/docs/html/open.png  
  inflating: glfw-3.2.1/docs/html/globals_defs_f.html  
  inflating: glfw-3.2.1/docs/html/moving_guide.html  
  inflating: glfw-3.2.1/docs/html/group__native.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_h.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_t.html  
  inflating: glfw-3.2.1/docs/html/vulkan_guide.html  
  inflating: glfw-3.2.1/docs/html/intro_8dox.html  
  inflating: glfw-3.2.1/docs/html/intro_guide.html  
  inflating: glfw-3.2.1/docs/html/group__joysticks.html  
  inflating: glfw-3.2.1/docs/html/globals_t.html  
  inflating: glfw-3.2.1/docs/html/tabs.css  
  inflating: glfw-3.2.1/docs/html/functions_vars.html  
  inflating: glfw-3.2.1/docs/html/globals_r.html  
  inflating: glfw-3.2.1/docs/html/splitbar.png  
  inflating: glfw-3.2.1/docs/html/group__keys.html  
  inflating: glfw-3.2.1/docs/html/compat_8dox.html  
  inflating: glfw-3.2.1/docs/html/group__buttons.html  
  inflating: glfw-3.2.1/docs/html/group__shapes.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_d.html  
  inflating: glfw-3.2.1/docs/html/bug.html  
 extracting: glfw-3.2.1/docs/html/sync_on.png  
  inflating: glfw-3.2.1/docs/html/glfw3native_8h_source.html  
  inflating: glfw-3.2.1/docs/html/spaces.svg  
  inflating: glfw-3.2.1/docs/html/group__context.html  
  inflating: glfw-3.2.1/docs/html/globals_i.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_l.html  
  inflating: glfw-3.2.1/docs/html/nav_h.png  
  inflating: glfw-3.2.1/docs/html/window_8dox.html  
 extracting: glfw-3.2.1/docs/html/folderopen.png  
  inflating: glfw-3.2.1/docs/html/globals_k.html  
  inflating: glfw-3.2.1/docs/html/doxygen.css  
  inflating: glfw-3.2.1/docs/html/globals_l.html  
 extracting: glfw-3.2.1/docs/html/bc_s.png  
  inflating: glfw-3.2.1/docs/html/input_guide.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_i.html  
 extracting: glfw-3.2.1/docs/html/doxygen.png  
  inflating: glfw-3.2.1/docs/html/jquery.js  
  inflating: glfw-3.2.1/docs/html/group__init.html  
  inflating: glfw-3.2.1/docs/html/compat_guide.html  
  inflating: glfw-3.2.1/docs/html/group__window.html  
  inflating: glfw-3.2.1/docs/html/main_8dox.html  
  inflating: glfw-3.2.1/docs/html/globals_type.html  
  inflating: glfw-3.2.1/docs/html/globals_p.html  
  inflating: glfw-3.2.1/docs/html/nav_g.png  
  inflating: glfw-3.2.1/docs/html/group__mods.html  
 extracting: glfw-3.2.1/docs/html/tab_b.png  
 extracting: glfw-3.2.1/docs/html/sync_off.png  
  inflating: glfw-3.2.1/docs/html/globals_j.html  
  inflating: glfw-3.2.1/docs/html/globals_b.html  
  inflating: glfw-3.2.1/docs/html/classes.html  
  inflating: glfw-3.2.1/docs/html/globals_m.html  
  inflating: glfw-3.2.1/docs/html/moving_8dox.html  
  inflating: glfw-3.2.1/docs/html/files.html  
  inflating: glfw-3.2.1/docs/html/context_guide.html  
  inflating: glfw-3.2.1/docs/html/closed.png  
  inflating: glfw-3.2.1/docs/html/globals_w.html  
  inflating: glfw-3.2.1/docs/html/news_8dox.html  
  inflating: glfw-3.2.1/docs/html/dir_4bcf8e981abe5adb811ce4f57d70c9af.html  
  inflating: glfw-3.2.1/docs/html/compile_guide.html  
  inflating: glfw-3.2.1/docs/html/monitor_8dox.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_p.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_c.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_j.html  
  inflating: glfw-3.2.1/docs/html/glfw3_8h.html  
  inflating: glfw-3.2.1/docs/html/dir_1f12d41534b9d9c99a183e145b58d6f3.html  
  inflating: glfw-3.2.1/docs/html/bdwn.png  
  inflating: glfw-3.2.1/docs/html/build_guide.html  
 extracting: glfw-3.2.1/docs/html/arrowdown.png  
  inflating: glfw-3.2.1/docs/html/globals_e.html  
  inflating: glfw-3.2.1/docs/html/globals_s.html  
  inflating: glfw-3.2.1/docs/html/globals_n.html  
  inflating: glfw-3.2.1/docs/html/group__input.html  
  inflating: glfw-3.2.1/docs/html/news.html  
  inflating: glfw-3.2.1/docs/html/globals_func.html  
  inflating: glfw-3.2.1/docs/html/index.html  
  inflating: glfw-3.2.1/docs/html/globals_f.html  
  inflating: glfw-3.2.1/docs/html/glfw3native_8h.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_v.html  
 extracting: glfw-3.2.1/docs/html/nav_f.png  
   creating: glfw-3.2.1/docs/html/search/
  inflating: glfw-3.2.1/docs/html/search/groups_6.js  
  inflating: glfw-3.2.1/docs/html/search/groups_0.js  
  inflating: glfw-3.2.1/docs/html/search/pages_6.html  
  inflating: glfw-3.2.1/docs/html/search/groups_9.html  
  inflating: glfw-3.2.1/docs/html/search/defines_0.html  
  inflating: glfw-3.2.1/docs/html/search/typedefs_0.html  
  inflating: glfw-3.2.1/docs/html/search/functions_0.html  
  inflating: glfw-3.2.1/docs/html/search/all_6.html  
  inflating: glfw-3.2.1/docs/html/search/files_5.js  
  inflating: glfw-3.2.1/docs/html/search/groups_7.js  
 extracting: glfw-3.2.1/docs/html/search/close.png  
  inflating: glfw-3.2.1/docs/html/search/all_2.js  
  inflating: glfw-3.2.1/docs/html/search/all_5.js  
  inflating: glfw-3.2.1/docs/html/search/files_2.js  
  inflating: glfw-3.2.1/docs/html/search/groups_2.js  
  inflating: glfw-3.2.1/docs/html/search/variables_2.js  
  inflating: glfw-3.2.1/docs/html/search/all_9.html  
  inflating: glfw-3.2.1/docs/html/search/defines_0.js  
  inflating: glfw-3.2.1/docs/html/search/all_8.html  
  inflating: glfw-3.2.1/docs/html/search/files_7.js  
  inflating: glfw-3.2.1/docs/html/search/all_b.js  
  inflating: glfw-3.2.1/docs/html/search/all_d.js  
  inflating: glfw-3.2.1/docs/html/search/groups_5.html  
  inflating: glfw-3.2.1/docs/html/search/groups_3.html  
 extracting: glfw-3.2.1/docs/html/search/mag_sel.png  
  inflating: glfw-3.2.1/docs/html/search/files_8.js  
  inflating: glfw-3.2.1/docs/html/search/variables_6.js  
  inflating: glfw-3.2.1/docs/html/search/files_0.html  
  inflating: glfw-3.2.1/docs/html/search/pages_8.html  
  inflating: glfw-3.2.1/docs/html/search/files_1.js  
  inflating: glfw-3.2.1/docs/html/search/pages_6.js  
  inflating: glfw-3.2.1/docs/html/search/all_7.html  
  inflating: glfw-3.2.1/docs/html/search/files_7.html  
  inflating: glfw-3.2.1/docs/html/search/all_0.js  
  inflating: glfw-3.2.1/docs/html/search/pages_7.html  
  inflating: glfw-3.2.1/docs/html/search/files_5.html  
  inflating: glfw-3.2.1/docs/html/search/all_a.html  
  inflating: glfw-3.2.1/docs/html/search/searchdata.js  
  inflating: glfw-3.2.1/docs/html/search/pages_0.js  
  inflating: glfw-3.2.1/docs/html/search/groups_4.html  
  inflating: glfw-3.2.1/docs/html/search/all_c.html  
  inflating: glfw-3.2.1/docs/html/search/groups_2.html  
  inflating: glfw-3.2.1/docs/html/search/variables_6.html  
  inflating: glfw-3.2.1/docs/html/search/search.js  
  inflating: glfw-3.2.1/docs/html/search/variables_4.js  
  inflating: glfw-3.2.1/docs/html/search/all_9.js  
  inflating: glfw-3.2.1/docs/html/search/all_d.html  
  inflating: glfw-3.2.1/docs/html/search/all_1.html  
  inflating: glfw-3.2.1/docs/html/search/pages_3.html  
  inflating: glfw-3.2.1/docs/html/search/pages_1.html  
  inflating: glfw-3.2.1/docs/html/search/variables_1.js  
  inflating: glfw-3.2.1/docs/html/search/groups_0.html  
  inflating: glfw-3.2.1/docs/html/search/pages_5.js  
  inflating: glfw-3.2.1/docs/html/search/pages_4.html  
  inflating: glfw-3.2.1/docs/html/search/files_6.js  
  inflating: glfw-3.2.1/docs/html/search/variables_5.html  
  inflating: glfw-3.2.1/docs/html/search/pages_4.js  
  inflating: glfw-3.2.1/docs/html/search/variables_3.js  
  inflating: glfw-3.2.1/docs/html/search/all_2.html  
  inflating: glfw-3.2.1/docs/html/search/groups_8.js  
  inflating: glfw-3.2.1/docs/html/search/variables_5.js  
  inflating: glfw-3.2.1/docs/html/search/pages_7.js  
  inflating: glfw-3.2.1/docs/html/search/classes_0.html  
  inflating: glfw-3.2.1/docs/html/search/search_m.png  
  inflating: glfw-3.2.1/docs/html/search/files_1.html  
  inflating: glfw-3.2.1/docs/html/search/pages_0.html  
  inflating: glfw-3.2.1/docs/html/search/files_4.js  
  inflating: glfw-3.2.1/docs/html/search/groups_7.html  
  inflating: glfw-3.2.1/docs/html/search/functions_0.js  
  inflating: glfw-3.2.1/docs/html/search/nomatches.html  
 extracting: glfw-3.2.1/docs/html/search/search_l.png  
  inflating: glfw-3.2.1/docs/html/search/files_4.html  
  inflating: glfw-3.2.1/docs/html/search/search.css  
  inflating: glfw-3.2.1/docs/html/search/all_0.html  
  inflating: glfw-3.2.1/docs/html/search/all_1.js  
  inflating: glfw-3.2.1/docs/html/search/all_5.html  
  inflating: glfw-3.2.1/docs/html/search/groups_8.html  
  inflating: glfw-3.2.1/docs/html/search/groups_4.js  
  inflating: glfw-3.2.1/docs/html/search/all_f.js  
  inflating: glfw-3.2.1/docs/html/search/variables_1.html  
  inflating: glfw-3.2.1/docs/html/search/all_7.js  
  inflating: glfw-3.2.1/docs/html/search/groups_3.js  
  inflating: glfw-3.2.1/docs/html/search/files_0.js  
  inflating: glfw-3.2.1/docs/html/search/all_b.html  
  inflating: glfw-3.2.1/docs/html/search/groups_6.html  
  inflating: glfw-3.2.1/docs/html/search/pages_2.js  
  inflating: glfw-3.2.1/docs/html/search/all_e.js  
 extracting: glfw-3.2.1/docs/html/search/search_r.png  
  inflating: glfw-3.2.1/docs/html/search/pages_1.js  
  inflating: glfw-3.2.1/docs/html/search/groups_1.js  
  inflating: glfw-3.2.1/docs/html/search/files_6.html  
  inflating: glfw-3.2.1/docs/html/search/all_e.html  
  inflating: glfw-3.2.1/docs/html/search/variables_0.js  
  inflating: glfw-3.2.1/docs/html/search/all_4.js  
  inflating: glfw-3.2.1/docs/html/search/typedefs_0.js  
  inflating: glfw-3.2.1/docs/html/search/files_3.html  
  inflating: glfw-3.2.1/docs/html/search/pages_8.js  
  inflating: glfw-3.2.1/docs/html/search/variables_4.html  
  inflating: glfw-3.2.1/docs/html/search/pages_3.js  
  inflating: glfw-3.2.1/docs/html/search/files_3.js  
  inflating: glfw-3.2.1/docs/html/search/pages_5.html  
  inflating: glfw-3.2.1/docs/html/search/all_6.js  
  inflating: glfw-3.2.1/docs/html/search/groups_5.js  
  inflating: glfw-3.2.1/docs/html/search/pages_2.html  
  inflating: glfw-3.2.1/docs/html/search/variables_0.html  
  inflating: glfw-3.2.1/docs/html/search/all_f.html  
  inflating: glfw-3.2.1/docs/html/search/groups_9.js  
  inflating: glfw-3.2.1/docs/html/search/all_a.js  
  inflating: glfw-3.2.1/docs/html/search/variables_3.html  
  inflating: glfw-3.2.1/docs/html/search/files_8.html  
  inflating: glfw-3.2.1/docs/html/search/variables_2.html  
  inflating: glfw-3.2.1/docs/html/search/groups_1.html  
  inflating: glfw-3.2.1/docs/html/search/classes_0.js  
  inflating: glfw-3.2.1/docs/html/search/files_2.html  
  inflating: glfw-3.2.1/docs/html/search/all_3.html  
  inflating: glfw-3.2.1/docs/html/search/all_3.js  
  inflating: glfw-3.2.1/docs/html/search/all_8.js  
  inflating: glfw-3.2.1/docs/html/search/all_c.js  
  inflating: glfw-3.2.1/docs/html/search/all_4.html  
  inflating: glfw-3.2.1/docs/html/globals_d.html  
  inflating: glfw-3.2.1/docs/html/glfw3_8h_source.html  
  inflating: glfw-3.2.1/docs/html/dynsections.js  
  inflating: glfw-3.2.1/docs/html/structGLFWimage.html  
  inflating: glfw-3.2.1/docs/html/annotated.html  
  inflating: glfw-3.2.1/docs/html/input_8dox.html  
 extracting: glfw-3.2.1/docs/html/arrowright.png  
  inflating: glfw-3.2.1/docs/html/quick_8dox.html  
  inflating: glfw-3.2.1/docs/html/globals_h.html  
  inflating: glfw-3.2.1/docs/html/globals_o.html  
  inflating: glfw-3.2.1/docs/html/compile_8dox.html  
  inflating: glfw-3.2.1/docs/html/functions.html  
  inflating: glfw-3.2.1/docs/html/modules.html  
 extracting: glfw-3.2.1/docs/html/folderclosed.png  
  inflating: glfw-3.2.1/docs/html/globals_defs_r.html  
  inflating: glfw-3.2.1/docs/html/monitor_guide.html  
  inflating: glfw-3.2.1/docs/html/globals_defs.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_m.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_g.html  
  inflating: glfw-3.2.1/docs/html/globals.html  
  inflating: glfw-3.2.1/docs/html/quick_guide.html  
  inflating: glfw-3.2.1/docs/html/structGLFWgammaramp.html  
  inflating: glfw-3.2.1/docs/html/group__errors.html  
  inflating: glfw-3.2.1/docs/html/group__monitor.html  
  inflating: glfw-3.2.1/docs/html/extra.css  
 extracting: glfw-3.2.1/docs/html/doc.png  
  inflating: glfw-3.2.1/docs/html/globals_c.html  
  inflating: glfw-3.2.1/docs/html/dir_351f617146de9499414a6c099ebbe0ca.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_n.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_s.html  
 extracting: glfw-3.2.1/docs/html/tab_s.png  
 extracting: glfw-3.2.1/docs/html/tab_a.png  
  inflating: glfw-3.2.1/docs/html/globals_g.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_k.html  
  inflating: glfw-3.2.1/docs/html/globals_defs_e.html  
  inflating: glfw-3.2.1/docs/html/group__vulkan.html  
  inflating: glfw-3.2.1/docs/html/pages.html  
  inflating: glfw-3.2.1/docs/html/context_8dox.html  
  inflating: glfw-3.2.1/docs/html/structGLFWvidmode.html  
 extracting: glfw-3.2.1/docs/html/tab_h.png  
  inflating: glfw-3.2.1/docs/html/globals_v.html  
  inflating: glfw-3.2.1/docs/html/window_guide.html  
  inflating: glfw-3.2.1/docs/html/vulkan_8dox.html  
  inflating: glfw-3.2.1/docs/intro.dox  
  inflating: glfw-3.2.1/docs/Doxyfile.in  
  inflating: glfw-3.2.1/cmake_uninstall.cmake.in  
   creating: glfw-3.2.1/src/
  inflating: glfw-3.2.1/src/init.c   
  inflating: glfw-3.2.1/src/win32_joystick.c  
  inflating: glfw-3.2.1/src/context.c  
  inflating: glfw-3.2.1/src/glx_context.c  
  inflating: glfw-3.2.1/src/glfw_config.h.in  
  inflating: glfw-3.2.1/src/win32_init.c  
  inflating: glfw-3.2.1/src/linux_joystick.h  
  inflating: glfw-3.2.1/src/glx_context.h  
  inflating: glfw-3.2.1/src/vulkan.c  
  inflating: glfw-3.2.1/src/cocoa_joystick.m  
  inflating: glfw-3.2.1/src/wl_init.c  
  inflating: glfw-3.2.1/src/cocoa_time.c  
  inflating: glfw-3.2.1/src/wl_window.c  
  inflating: glfw-3.2.1/src/x11_init.c  
  inflating: glfw-3.2.1/src/x11_monitor.c  
  inflating: glfw-3.2.1/src/win32_tls.c  
  inflating: glfw-3.2.1/src/mir_window.c  
  inflating: glfw-3.2.1/src/wgl_context.h  
  inflating: glfw-3.2.1/src/mir_monitor.c  
  inflating: glfw-3.2.1/src/win32_window.c  
  inflating: glfw-3.2.1/src/nsgl_context.h  
  inflating: glfw-3.2.1/src/egl_context.c  
  inflating: glfw-3.2.1/src/posix_tls.h  
 extracting: glfw-3.2.1/src/glfw3Config.cmake.in  
  inflating: glfw-3.2.1/src/cocoa_monitor.m  
  inflating: glfw-3.2.1/src/xkb_unicode.c  
  inflating: glfw-3.2.1/src/xkb_unicode.h  
  inflating: glfw-3.2.1/src/win32_monitor.c  
  inflating: glfw-3.2.1/src/mir_platform.h  
  inflating: glfw-3.2.1/src/win32_time.c  
  inflating: glfw-3.2.1/src/cocoa_joystick.h  
  inflating: glfw-3.2.1/src/internal.h  
  inflating: glfw-3.2.1/src/CMakeLists.txt  
  inflating: glfw-3.2.1/src/posix_time.h  
  inflating: glfw-3.2.1/src/glfw3.pc.in  
  inflating: glfw-3.2.1/src/win32_platform.h  
  inflating: glfw-3.2.1/src/wl_platform.h  
  inflating: glfw-3.2.1/src/mir_init.c  
  inflating: glfw-3.2.1/src/cocoa_platform.h  
  inflating: glfw-3.2.1/src/monitor.c  
  inflating: glfw-3.2.1/src/egl_context.h  
  inflating: glfw-3.2.1/src/posix_tls.c  
  inflating: glfw-3.2.1/src/linux_joystick.c  
  inflating: glfw-3.2.1/src/wgl_context.c  
  inflating: glfw-3.2.1/src/input.c  
  inflating: glfw-3.2.1/src/win32_joystick.h  
  inflating: glfw-3.2.1/src/cocoa_window.m  
  inflating: glfw-3.2.1/src/x11_window.c  
  inflating: glfw-3.2.1/src/window.c  
  inflating: glfw-3.2.1/src/nsgl_context.m  
  inflating: glfw-3.2.1/src/cocoa_init.m  
  inflating: glfw-3.2.1/src/posix_time.c  
  inflating: glfw-3.2.1/src/x11_platform.h  
  inflating: glfw-3.2.1/src/wl_monitor.c  
  inflating: glfw-3.2.1/CMakeLists.txt  
  inflating: glfw-3.2.1/README.md    
   creating: glfw-3.2.1/.github/
  inflating: glfw-3.2.1/.github/CONTRIBUTING.md  
   creating: glfw-3.2.1/CMake/
  inflating: glfw-3.2.1/CMake/amd64-mingw32msvc.cmake  
  inflating: glfw-3.2.1/CMake/MacOSXBundleInfo.plist.in  
  inflating: glfw-3.2.1/CMake/i586-mingw32msvc.cmake  
  inflating: glfw-3.2.1/CMake/i686-w64-mingw32.cmake  
   creating: glfw-3.2.1/CMake/modules/
  inflating: glfw-3.2.1/CMake/modules/FindMir.cmake  
  inflating: glfw-3.2.1/CMake/modules/FindWaylandProtocols.cmake  
  inflating: glfw-3.2.1/CMake/modules/FindXKBCommon.cmake  
  inflating: glfw-3.2.1/CMake/modules/FindVulkan.cmake  
  inflating: glfw-3.2.1/CMake/i686-pc-mingw32.cmake  
  inflating: glfw-3.2.1/CMake/x86_64-w64-mingw32.cmake  
   creating: glfw-3.2.1/tests/
  inflating: glfw-3.2.1/tests/reopen.c  
  inflating: glfw-3.2.1/tests/threads.c  
  inflating: glfw-3.2.1/tests/cursor.c  
  inflating: glfw-3.2.1/tests/vulkan.c  
  inflating: glfw-3.2.1/tests/title.c  
  inflating: glfw-3.2.1/tests/windows.c  
  inflating: glfw-3.2.1/tests/events.c  
  inflating: glfw-3.2.1/tests/monitors.c  
  inflating: glfw-3.2.1/tests/msaa.c  
  inflating: glfw-3.2.1/tests/glfwinfo.c  
  inflating: glfw-3.2.1/tests/timeout.c  
  inflating: glfw-3.2.1/tests/sharing.c  
  inflating: glfw-3.2.1/tests/tearing.c  
  inflating: glfw-3.2.1/tests/CMakeLists.txt  
  inflating: glfw-3.2.1/tests/gamma.c  
  inflating: glfw-3.2.1/tests/empty.c  
  inflating: glfw-3.2.1/tests/clipboard.c  
  inflating: glfw-3.2.1/tests/joysticks.c  
  inflating: glfw-3.2.1/tests/icon.c  
  inflating: glfw-3.2.1/tests/iconify.c  
   creating: glfw-3.2.1/deps/
  inflating: glfw-3.2.1/deps/glad.c  
   creating: glfw-3.2.1/deps/glad/
  inflating: glfw-3.2.1/deps/glad/glad.h  
   creating: glfw-3.2.1/deps/vulkan/
  inflating: glfw-3.2.1/deps/vulkan/vulkan.h  
  inflating: glfw-3.2.1/deps/vulkan/vk_platform.h  
   creating: glfw-3.2.1/deps/KHR/
  inflating: glfw-3.2.1/deps/KHR/khrplatform.h  
  inflating: glfw-3.2.1/deps/getopt.c  
  inflating: glfw-3.2.1/deps/tinycthread.h  
   creating: glfw-3.2.1/deps/mingw/
  inflating: glfw-3.2.1/deps/mingw/_mingw_dxhelper.h  
  inflating: glfw-3.2.1/deps/mingw/xinput.h  
  inflating: glfw-3.2.1/deps/mingw/dinput.h  
  inflating: glfw-3.2.1/deps/linmath.h  
  inflating: glfw-3.2.1/deps/tinycthread.c  
  inflating: glfw-3.2.1/deps/getopt.h  
cd glfw-3.2.1 && gcc . \
		-DCMAKE_INSTALL_PREFIX="" -DBUILD_SHARED_LIBS=ON \
		-DGLFW_USE_CHDIR=OFF -DGLFW_USE_MENUBAR=ON -DGLFW_USE_RETINA=ON
ld: can't map file, errno=22 file '.' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [glfw-3.2.1] Error 1
make: *** [dep] Error 2
```

**Comment by AndrewBelt** [comment]
Oh, no, I'm saying that you need the 10.7 SDK to be able to follow the instructions on the README. https://github.com/VCVRack/Rack#mac Otherwise plugin binaries you build won't work other people's Rack, and you won't be able to use other people's binaries.

I should install 10.13 on my laptop and fix these problems though, since not everyone who builds it wants to make plugins. But they should be aware that other plugins are probably not ABI compatable.

**Comment by Euphorbium** [comment]
glfw is available through brew. Would it be possible to use it, instead of building it from source?

**Comment by AndrewBelt** [comment]
You might be able to, but I won't support issues originating from global installs. The reason is that 98% of the users are musicians, not PC admins, who need a standalone package to click on, so I've made the build system tightly coupled to the dep and ext folders. Maybe later I'll officially support global installs, but every method everyone has proposed breaks the build for the standalone distributables.

**Comment by antoniograzioli** [comment]
I had similar problems yesterday and was able to compile on Mac, downloaded Xcode 4.x and extracted the OSX10.7 folder and copied manually.
I am pretty sure portaudio  looks for SDKs from 10.5 to 10.12 and fails because you now have 10.13 installed...

**Comment by AndrewBelt** [comment]
If it's a problem with portaudio, could you suggest a change to `dep/Makefile` which doesn't break the build for the rest of us? It might be a month before I can get around to it.

**Comment by antoniograzioli** [comment]
I noticed that the configure file in dep/portaudio searches fo SDKs from 10.5 to 10.12, otherwise it fails...and since we have now 10.13 it cannot find it.

portion of code follows (lines +/- 15840-60)

`elif xcodebuild -version -sdk macosx10.10 Path >/dev/null 2>&1 ; then
                 mac_version_min="-mmacosx-version-min=10.4"
                 mac_sysroot="-isysroot `xcodebuild -version -sdk macosx10.10 Path`"
              elif xcodebuild -version -sdk macosx10.11 Path >/dev/null 2>&1 ; then
                 mac_version_min="-mmacosx-version-min=10.4"
                 mac_sysroot="-isysroot `xcodebuild -version -sdk macosx10.11 Path`"
              elif xcodebuild -version -sdk macosx10.12 Path >/dev/null 2>&1 ; then
                 mac_version_min="-mmacosx-version-min=10.4"
                 mac_sysroot="-isysroot `xcodebuild -version -sdk macosx10.12 Path`"
              else
                 as_fn_error $? "Could not find 10.5 to 10.12 SDK." "$LINENO" 5
              fi`


As @AndrewBelt suggested yesterday (and good advice it was) it's better to use SDK 10.7 (download a legacy copy of Xcode 4.x and manually extract the SDK)

**Comment by Euphorbium** [comment]
Do I need to manually install old version of xcode? Is it possible to keep both the current version and the old one? I am jumping through a lot of hoops to get that ancient deprecated version of the sdk.

**Comment by antoniograzioli** [comment]
I manually copied SDK 10.7 and solved all my problems
you can keep the current version

**Comment by AndrewBelt** [comment]
It's pretty easy.

	# After cloning the xcodelegacy project:
	chmod +x XcodeLegacy.sh
	./XcodeLegacy.sh -osx107 build
	# Here it will complain about needing the Xcode DMG. Download it and move it to this directory and rerun the command.
	# Automatically copy the SDK to your "modern" xcode.
	sudo ./XcodeLegacy.sh -osx107 install
	# You can now delete everything in this folder

**Comment by antoniograzioli** [comment]
@AndrewBelt yes, in my case that didn't work...

**Comment by AndrewBelt** [comment]
It's still a bit difficult to obtain this SDK. You can thank Apple for that. Someone should *cough* host the SDK somewhere. There's this project (https://github.com/phracker/MacOSX-SDKs) but for some reason it doesn't work for me. Maybe it would help you though.

**Comment by antoniotuzzi** [comment]
What is the problem using the "**/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk**" (that points always to last version) standard in the makefiles (or dep)
but using the limit at 10.7 ("_-mmacosx-version-min=10.7_")?
I remember I've changed just this in "compile.mk" and "dep/Makefile" and recompiled everything

**Comment by antoniograzioli** [comment]
/XcodeLegacy.sh has all URSL to Sdk in it

**Comment by Euphorbium** [comment]
It does not complain about needing the DMG. And when I manually donwload it and place it in the folder it does not change. All I am getting is `*** Info: found Xcode >= 4.3`. This is probably due to me having a current version of Xcode. I have tried uninstalling it and installing an old one, but then my system breaks, so this is not an option.

**Comment by AndrewBelt** [comment]
@antoniotuzzi Actually, I forgot the reason for doing that. I will try building on 10.12 without `-isysroot` and test it on 10.7...

**Comment by Euphorbium** [comment]
@antoniotuzzi That seems like a miracle solution, unfortunately I am still unable to build glfw. Could you provide some more info about the version of your cmake? 

```
[ 14%] Linking C shared library libglfw.dylib
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /usr/local/Cellar/cmake/3.9.3/bin/cmake
  Expected in: /usr/lib/libSystem.B.dylib

make[4]: *** [src/libglfw.dylib] Abort trap: 6
make[4]: *** Deleting file `src/libglfw.dylib'
make[3]: *** [src/CMakeFiles/glfw.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [lib/libglfw.dylib] Error 2
make: *** [dep] Error 2
```

**Comment by antoniotuzzi** [comment]
@Euphorbium 
_cmake version 3.9.2
CMake suite maintained and supported by Kitware (kitware.com/cmake)._

**Comment by antoniotuzzi** [comment]
@Euphorbium FYI
[lazy symbol binding failed: Symbol not found: _utimensat](https://forums.developer.apple.com/thread/87097)

**Comment by AndrewBelt** [comment]
@antoniotuzzi Well, it looks like a full build from scratch on 10.12 without -isysroot still runs on 10.7. Not sure why I added that requirement! Fixed in 00fed6326d990d2957715d2a1634641813c55405

**Comment by antoniotuzzi** [comment]
@AndrewBelt 👍 
there is another small problem in the build (MAC)
is some system WGETting "https://curl.haxx.se/download/curl-7.54.1.tar.gz" fails with

> --2017-09-22 09:52:39--  https://curl.haxx.se/download/curl-7.54.1.tar.gz
> Resolving curl.haxx.se... 151.101.194.49, 151.101.2.49, 151.101.66.49, ...
> Connecting to curl.haxx.se|151.101.194.49|:443... connected.
> OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
> Unable to establish SSL connection.
> make: *** [lib/libcurl.dylib] Error 4

probably the source has a wrong certificate

I suggest to change the source to
**https://github.com/curl/curl/files/1101227/curl-7.54.1.tar.gz**

(that works flawlessly)

**Comment by AndrewBelt** [comment]
@antoniotuzzi Weird, it works for me on Linux and Mac. I've changed it in 1a50e06b791dc4a49252df728f18253f1feb05f0 anyway since I trust Github's uptime more than haxx.se's.

**Comment by antoniotuzzi** [comment]
@AndrewBelt FYI: I recompiled everything from scratch without any change
(I'm still on sdk 12... Xcode 8.3.3)

**Comment by Euphorbium** [comment]
I was able to build the dependancies (on Xcode version 9.0), with Xcode Xcode 4.6.3  libraries installed using xcodelegacy, using CMake 3.9.2 installed via homebrew.

Now when running `make` I get 

```
macbooks-MacBook-Pro:Rack euphorbium$ make
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/app.cpp.o src/app.cpp
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/dsp.cpp.o src/dsp.cpp
src/dsp.cpp:8:13: warning: unused variable 'minblep_16_32'
      [-Wunused-const-variable]
const float minblep_16_32[] = {
            ^
1 warning generated.
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/engine.cpp.o src/engine.cpp
src/engine.cpp:101:8: warning: unused variable 'duration' [-Wunused-variable]
                auto duration = std::chrono::nanoseconds((long) (0.10 * ...
                     ^
1 warning generated.
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/gui.cpp.o src/gui.cpp
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/main.cpp.o src/main.cpp
c++ -Iinclude -Idep/include -Idep/lib/libzip/include -DVERSION=dev -MMD -O3 -march=core2 -ffast-math -g -Wall -DARCH_MAC -mmacosx-version-min=10.7 -DAPPLE -stdlib=libc++ -std=c++11 -stdlib=libc++ -c -o build/src/plugin.cpp.o src/plugin.cpp
In file included from src/plugin.cpp:11:
include/zip.h:59:10: fatal error: 'zipconf.h' file not found
#include <zipconf.h>
         ^~~~~~~~~~~
1 error generated.
make: *** [build/src/plugin.cpp.o] Error 1
```

**Comment by Euphorbium** [comment]
here is the complete output of dependancy build. https://gist.github.com/Euphorbium/5f156eab9ff65b164c494f364ef6f4f8

**Comment by AndrewBelt** [comment]
Something's weird with your dep path. Ah! I'm not setting the PWD of dep/Makefile correctly. Fixed in 3185ae955edfad040c39b10874597aefedb2b952. Pull and rebuild.

**Comment by Euphorbium** [comment]
I have finally built it! Readme should be updated, because currently it appears that downloading old version of SDK is optional. It is not optional.

**Comment by AndrewBelt** [comment]
Actually using an old SDK is no longer required, so I'll remove that line.

**Comment by Euphorbium** [comment]
It IS required. I did try to build without it, and some dependancy failed to build. And yes, I was up to date, on the latest commit.

**Comment by PatchworkBoy** [comment]
libcurl still failing with github URL... 

```
 CC       vtls/libcurl_la-mbedtls.lo
connect.c:1086:12: error: 'connectx' is only available on macOS 10.11 or newer [-Werror,-Wunguarded-availability]
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
/usr/include/sys/socket.h:713:5: note: 'connectx' has been explicitly marked partial here
int connectx(int, const sa_endpoints_t *, sae_associd_t, unsigned int,
    ^
connect.c:1086:12: note: enclose 'connectx' in a __builtin_available check to silence this warning
      rc = connectx(sockfd, &endpoints, SAE_ASSOCID_ANY,
           ^~~~~~~~
1 error generated.
make[4]: *** [libcurl_la-connect.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [lib/libcurl.dylib] Error 2
make: *** [dep] Error 2
```

Also fails with haxx url... same error.

**Comment by AndrewBelt** [comment]
@PatchworkBoy Does homebrew for example pull a newer version of curl, or do they have a patch file? How do they handle building curl?

**Comment by PatchworkBoy** [comment]
Hang on - am just looking at https://github.com/JuliaLang/julia/issues/23980 which recommends switching to 56.0, which I’m currently testing...

**Comment by modlfo** [comment]
I'm closing this issue because it seems fixed/outdated. Feel free to comment if not.
