### ISSUE TITLE
Cannot log in; clicking "log in" deletes password with no notification

### ISSUE THREAD

**Issue by tel** [VCVRack/Rack#473]
OS (if applicable): OS X
Version (or "dev" if compiling from source): 0.5.0

Clicking "log in" after entering email and password just deletes my password and provides no feedback. I am fairly confident that this is the correct password, but even if it's not I would expect some kind of notification that it failed.

**Comment by tel** [comment]
Restarting my computer fixed this—so it's likely something specific and weird about my system at the time. Leaving this open just for reporting purposes and to note that the error message flow was confusing. Not sure how to debug it at this point, however.

**Comment by AndrewBelt** [comment]
What do you mean by "deletes my password"?

Ah, you means it clears the password text box. Yes, I should fix that.

**Comment by http404error** [comment]
Just to be sure, note that the password field _should_ be cleared if the credentials were incorrect, in accordance with usability standards. But not clearing until a response is received is sensible as well.

**Comment by tel** [comment]
Yes, clears the box. I think if the is wrong it'd be nice to receive some kind of visual notification as to the reason (even as simple as turning the box red momentarily). I also believe very strongly that the password was correct (checked it several times, it worked on the website, used the same process to enter it after restarting and it worked), so perhaps this error had to do with server connection or something else of that nature?

**Comment by luizen** [comment]
I have the same issue. Windows 10 and behind a corporate proxy. Maybe that has something to do with it? Any logs available?

**Comment by pgroce** [comment]
Still happens in the 1.* series. It doesn't work behind a web proxy, does work otherwise. Also happens with plugins.

As of 1.0, VCVRack returns some feedback indicating the login process is finished, even if it is unsuccessful. So I can now say the login behind a proxy returns immediately with "No response from server." (It is likely getting an unexpected error response from our proxy, which often does this but apparently can't transparently proxy for some reason. That's someone else's bug report. :) )

I haven't looked into it too closely, but it seems VCVRack uses libcurl for networking, and libcurl requires some special handling to honor proxies: https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html 

That said, it should honor http_proxy and friends if they're set, but when I invoke `Rack.app/Contents/MacOS/Rack` from the command-line, I get the same results. Perhaps Rack doesn't inherit the environment from the shell?

Bottom-line: This is a long-standing issue, and remains an issue as of 1.1.1, at least.
